steps:
  - id: preview
    label: ":pulumi: Preview"
    command: |
      npm install
      pulumi preview
    plugins:
      pulumi:
        use-oidc: true
        audience: "urn:pulumi:org:cnunciato"
        pulumi-token-type: "urn:pulumi:token-type:access_token:personal"
        pulumi-token-scope: "user:cnunciato"

  - block: ":pulumi: Deploy?"
    depends_on: preview
    allowed_teams:
      - trusted-humans

  - label: ":pulumi: Update"
    command: |
      npm install
      pulumi preview
    plugins:
      pulumi:
        use-oidc: true
        audience: "urn:pulumi:org:cnunciato"
        pulumi-token-type: "urn:pulumi:token-type:access_token:personal"
        pulumi-token-scope: "user:cnunciato"
